const AWSServices = () => {

    // const cards = [
    //     {
    //         title: <h3 className="">Cloud Optimization Cost & Management</h3>,
    //         texts: [
    //             "Rightsizing Recommendations",
    //             "Trusted Advisor Cost Optimization", 
    //             "Billing Conductor Implementation"
    //         ],
    //         icon: "/AWS/management.svg"
    //     },
    //     {
    //         title: <h3 className="">Security & Governance</h3>,
    //         texts: [
    //             "Web Application Firewall (WAF) Setup",
    //             "Identity & Access Management (IAM)", 
    //             "Network Firewall Configuration"
    //         ],
    //         icon: "/AWS/management.svg"
    //     },
    //     {
    //         title: <h3 className="">Generativee AI with AWS Bedrock</h3>,
    //         texts: [
    //             "Foundation Model Selection and Integration",
    //             "Custom Model Fine-tuning", 
    //             "Retrieval Augmented Generation (RAG) Implementation",
    //             "AI Agent Development for Complex Tasks",
    //             "Secure and Compliant AI Application Deployment",
    //         ],
    //         icon: "/AWS/bedrock.svg"
    //     },
    //     {
    //         title: <h3 className="">Data Analytics & Storage</h3>,
    //         texts: [
    //             "Amazon Kinesis Data Analytics",
    //             "Amazon S3 Storage Management", 
    //             "Amazon MemoryDB for Redis",
    //         ],
    //         icon: "/AWS/storage.svg"
    //     },
    //     {
    //         title: <h3 className="">Application Modernization</h3>,
    //         texts: [
    //             "Serverless Application Development",
    //             "Microservices Architecture Design", 
    //             "Container Orchestration (Amazon EKS Anywhere)",
    //         ],
    //         icon: "/AWS/modernization.svg"
    //     },
    //     {
    //         title: <h3 className="">Migration & Disaster Recovery</h3>,
    //         texts: [
    //             "Database Migration Service",
    //             "Elastic Disaster Recovery Solutions", 
    //             "Cloud Governance & Multi-cloud Strategies",
    //         ],
    //         icon: "/AWS/recovery.svg"
    //     },
    //     {
    //         title: <h3 className="">Specialized tools & Features</h3>,
    //         texts: [
    //             "Amazon Route 53 Resolver DNS Firewall",
    //             "Amazon FSx for OpenZFS", 
    //             "Amazon Braket Quantum Computing",
    //         ],
    //         icon: "/AWS/features.svg"
    //     },

    // ]
    return (
        <section className="">
            <h3 className="">Our Specialized AWS
                Services </h3>
        </section>
    );
}


export default AWSServices;